spring:
  datasource:
    url: jdbc:oracle:thin:@10.99.53.30:1521:UATDB7
    username: RBL_MOCK7
    password: RBL_MOCK7
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      connection-timeout: 30000
      pool-name: HikariPool_INSTANT_CASH_API_SERVICE
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        format_sql: true
        generate_statistics: true
        cache:
          use_second_level_cache: false
#          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

#Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always




logging:
  level:
    org:
    hibernate:
      SQL: debug
      type: trace
    com:
    example:
      demo:
      controller: debug
      service: debug
      repository: debug


bank:
  code: 185
  name: Bank Limited

  
running:
  server: uat

  
#RIA_CASH_EXCHANGE_HOUSE_PROPERTIES
EXCHANGE_HOUSE_BRANCH_USER: CBSRMS
EXCHANGE_HOUSE_BRANCH_USER_DEVICE_ID: HOST

INSTANT_CASH_API_USER_ID: BD00002622
INSTANT_CASH_API_USER_RECEIVE_PAYMENT_API_USER_ID: BD90000000
INSTANT_CASH_API_USER_PASSWORD: CGE982

  #Scheduler on/off
IS_INSTANT_CASH_API_SCHEDULER_ENABLED: true
IS_RIA_API_SCHEDULER_ENABLED: true
API_SCHEDULER_INTERVAL: 120000

